misogoro/co/urls.py
from django.urls import path
from . import views

#path urls for expert app.
urlpatterns = [
    path('',views.DashboardcoView, name='dashboardco_url'),
    path('caseassigned/',views.CaseAssignedView, name='caseassigned_url'),
    path('casestatus/',views.CaseStatusView, name='casestatus_url'),
    path('addcasestatus/',views.AddCaseStatusView.as_view(), name='addcasestatus_url'),
    path('casestatusview/<str:pk>',views.CaseStatusDetailView, name='casestatusview_url'),
    path('myprofile/',views.MyProfileView, name='myprofile_url'),
    
    #report management.....
    path('policereport/',views.PoliceReportView, name='policereport_url'),
    path('explorerreport/',views.ExplorerReportView, name='explorerreport_url'),
    path('casereport/',views.CaseReportView, name='casereport_url'),
    path('criminalcase/',views.CriminalCaseView, name='criminalcase_url'),
    

]

misogoro/misogoro/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
#redirecting to home page..
from django.views.generic import RedirectView

urlpatterns = [
    path('homepage_url/',include('account.urls')),
    path('',RedirectView.as_view(url='/homepage_url/')),

    path('admin/', admin.site.urls),
    path('', include('account.urls')),
    path('police/',include('police.urls')),
    path('explorer/',include('explorer.urls')),
    path('co/',include('co.urls')),
] 
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root =settings.MEDIA_ROOT)

misogoro/co/models.py
from django.db import models
from django.core.validators import FileExtensionValidator
from django.contrib.auth.models import User,Group
from django.utils.translation import gettext as _

# Create your models here.
class Role(Group):
    class Meta:
        proxy = True
        app_label = 'auth'
        verbose_name = _('Role')

class UserInfo(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE,blank=True,null=True)
    phone = models.CharField(max_length=15,null=False,blank=False,unique=True)
    address = models.CharField(max_length=20,null=False,blank=False)
    occupation = models.CharField(max_length=20,null=False,blank=False)
    tribe = models.CharField(max_length=20,null=False,blank=False)
    age = models.IntegerField(null=False,blank=False)
    empNo = models.CharField(max_length=20,null=False,blank=False)

    def __str__(self):
        return self.phone

class Profile(models.Model):
    User = models.OneToOneField(User, on_delete=models.CASCADE, blank=True,null=True)
    image = models.FileField(upload_to='uploads/profile', validators=[FileExtensionValidator(allowed_extensions=['png','jpg','jpeg'])])
    date_updated = models.DateField(auto_now=True)

    def __str__(self):
        return self.User.username

class Case(models.Model):
    case_no = models.IntegerField(null=False,blank=False,unique=True)
    reporter = models.CharField(max_length=30,blank=False,null=False)
    case_site = models.CharField(max_length=50,blank=False,null=False)
    phoneNo = models.CharField(max_length=15,null=True,blank=False)
    description = models.TextField()
    created_at = models.DateField(auto_now_add=True)
    status = models.BooleanField(default=False)

    def __str__(self):
        return str(self.case_no)

class CaseAssignment(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL,blank=True,null=True)
    case = models.OneToOneField(Case,on_delete=models.CASCADE,blank=True,null=True)
    date_assigned = models.DateField(auto_now_add=True)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return str(self.case)

class CaseStatus(models.Model):
    caseassignment = models.ForeignKey(CaseAssignment,on_delete=models.CASCADE,blank=True,null=True)
    datetime = models.DateField(auto_now_add=True)
    contact = models.CharField(max_length=15,blank=False,null=False)
    description = models.TextField()

    def __str__(self):
        return self.caseassignment.user.username +" || " +str(self.datetime)

misogoro/co/forms.py
from django.db.models import Model, fields
from django.forms import ModelForm
from co.models import *

class CaseViewForm(ModelForm):
    class Meta:
        model = CaseStatus
        fields = "__all__"

misogoro/co/views.py
from django.shortcuts import render
from account.decolators import un_co
from co.models import *

from django.views.generic.edit import CreateView
from django.views.generic import DetailView
from django.urls import reverse

from co.forms import CaseViewForm

# Create your views here.
@un_co
def DashboardcoView(request):
    
    context = {}
    return render(request, 'co/dashboardco.html', context)

def CaseAssignedView(request):
    assignedcase = CaseAssignment.objects.all()
    
    context = {'data':assignedcase}
    return render(request, 'co/caseassignment.html',context)
    
def CaseStatusView(request):
    statuslist = CaseStatus.objects.all()
    
    context = {'statuslist':statuslist}
    return render(request, 'co/casestatus.html', context)

class AddCaseStatusView(CreateView):
 
    model = CaseStatus
    fields = '__all__'
    template_name = 'co/addcasestutus.html'

    def get_success_url(self):
        return reverse('casestatus_url')

def CaseStatusDetailView(request, pk):
    dada = CaseStatus.objects.get(id=pk)
    datas = CaseViewForm(instance=dada)

    context = {'dat':datas}
    return render(request, 'co/casestatusdetail.html', context)

def MyProfileView(request):
    
    context = {}
    return render(request, 'co/myprofile.html', context)

def PoliceReportView(request):
    
    context = {}
    return render(request, 'co/policereport.html', context)

def ExplorerReportView(request):
    
    context = {}
    return render(request, 'co/explorerreport.html', context)

def CaseReportView(request):
    
    context = {}
    return render(request, 'co/casereport.html', context)

def CriminalCaseView(request):
    
    context = {}
    return render(request, 'co/criminalcase_report.html', context)

misogoro/templates/co/addcasestutus.html
{% extends 'co/cobase.html' %}

{% block content %}
{% load crispy_forms_tags %}
{% load static %}

<div class="container mb-5">
    <div class="row justify-content-center">
        <div class="col-md-6 col-sm-12 col-xs-12">
            <form method="post" style="border: 4px; background-color:rgb(139, 145, 139); padding:10px; border-radius: 5px;">
                {% csrf_token %}
                <legend class="border-bottom mb-4"><h3 style="color: blue;"><b>Add Case Status</b></h3></legend>
                {{ form | crispy }}
                <button class="btn btn-primary btn-block mt-3 " type="submit">
                    Save
                </button>
                <!-- <input type="reset" class="btn btn-primary btn-block mt-3 " value="Refresh"> -->
                <a class="btn btn-secondary form-control" href="{% url 'casestatus_url' %}">back</a>
            </form>
        </div>
    </div>
</div>


{% endblock content %}

misogoro/templates/co/caseassignment.html
{% extends 'co/cobase.html' %}

{% block content %}
{% load static %}

<div class="card">
    <div class="card-header">
      <h3 class="card-title">Data table for assigned cases:</h3>
    </div>
    <!-- /.card-header -->
    <div class="card-body">
      <table id="example1" class="table table-bordered table-striped">
        <thead>
        <tr>
          <th>EXPLORER</th>
          <th>CASE</th>
          <th>CASE ASSIGNED</th>
          <th>STATUS</th>
        </tr>
        </thead>
        <tbody>
        {% for dat in data %}
        <tr>
          <td>{{dat.user}}</td>
          <td>{{dat.case}}</td>
          <td>{{dat.date_assigned}}</td>
          {% if dat.is_active == True %}
          <td style="color:rgb(21, 6, 110)"><b>active</b></td>
          {% else %}
          <td style="color:rgb(238, 14, 14)"><b>danied</b></td>
          {% endif %}
        </tr>
        {% endfor %}
        </tbody>
        <tfoot>
        <tr>
          <th>EXPLORER</th>
          <th>CASE</th>
          <th>CASE ASSIGNED</th>
          <th>STATUS</th>
        </tr>
        </tfoot>
      </table>
    </div>
    <!-- /.card-body -->
  </div>

{% endblock content %}

misogoro/templates/co/casereport.html
{% extends 'co/cobase.html' %}

{% block content %}


<h2>case report</h2>

{% endblock content %}

misogoro/templates/co/casestatus.html
{% extends 'co/cobase.html' %}

{% block content %}

{% load static %}

<div class="card">
    <div class="card-header">
      <h3 class="card-title">Data table for case status report:</h3>
      {% if perms.auth.add_casestatus %}
      <a href="{% url 'addcasestatus_url' %}" class="btn btn-primary float-right">
        Add Case Status:
      </a>
      {% endif %}
    </div>
    <!-- /.card-header -->
    <div class="card-body">
      <table id="example1" class="table table-bordered table-striped">
        <thead>
        <tr>
          <th>CASE_NO</th>
          <th>DATE TIME</th>
          <th>CONTACT</th>
          <th>DESCRIPTION</th>
          <th>VIEW</th>
        </tr>
        </thead>
        <tbody>
        {% for status in statuslist %}
        <tr>
          <td>{{status.caseassignment}}</td>
          <td>{{status.datetime}}</td>
          <td>{{status.contact}}</td>
          <td>{{status.description}} </td>
          <td>
            <a href="{% url 'casestatusview_url' status.id %}" class="fa fa-eye" title="View Case Status."></a>
          </td>
        </tr>
        {% endfor %}
        </tbody>
        <tfoot>
        <tr>
          <th>CASE NAME</th>
          <th>DATE TIME</th>
          <th>CONTACT</th>
          <th>DESCRIPTION</th>
          <th>VIEW</th>
        </tr>
        </tfoot>
      </table>
    </div>
    <!-- /.card-body -->
  </div>

{% endblock content %}

misogoro/templates/co/casestatusdetail.html
{% extends 'co/cobase.html' %}

{% block content %}
{% load crispy_forms_tags %}
{% load static %}

<div class="container mb-5">
    <div class="row justify-content-center">
        <div class="col-md-6 col-sm-12 col-xs-12">
            <form method="post" style="border: 4px; background-color:rgb(119, 119, 134); padding:10px; border-radius: 5px;">
                {% csrf_token %}
                <legend class="border-bottom mb-4"><h3 style="color: blue;"><b>Case Status Detail View</b></h3></legend>
                {{ dat | crispy }}
                <!-- <input type="reset" class="btn btn-primary btn-block mt-3 " value="Refresh"> -->
                <a class="btn btn-warning form-control" href="{% url 'casestatus_url' %}">back</a>
            </form>
        </div>
    </div>
</div>


{% endblock content %}

misogoro/templates/co/cobase.html
<!DOCTYPE html>
<html lang="en">
{% load static %}

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Police | Dashboard</title>

  <!-- Google Font: Source Sans Pro -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="{% static 'plugins/fontawesome-free/css/all.min.css' %}">
  <!-- Ionicons -->
  <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
  <!-- Tempusdominus Bootstrap 4 -->
  <link rel="stylesheet" href="{% static 'plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css' %}">
  <!-- iCheck -->
  <link rel="stylesheet" href="{% static 'plugins/icheck-bootstrap/icheck-bootstrap.min.css' %}">
  <!-- JQVMap -->
  <link rel="stylesheet" href="{% static 'plugins/jqvmap/jqvmap.min.css' %}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{% static 'dist/css/adminlte.min.css' %}">
  <!-- overlayScrollbars -->
  <link rel="stylesheet" href="{% static 'plugins/overlayScrollbars/css/OverlayScrollbars.min.css' %}">
  <!-- Daterange picker -->
  <link rel="stylesheet" href="{% static 'plugins/daterangepicker/daterangepicker.css' %}">
  <!-- summernote -->
  <link rel="stylesheet" href="{% static 'plugins/summernote/summernote-bs4.min.css' %}">

  <!-- DataTables -->
  <link rel="stylesheet" href="{% static 'plugins/datatables-bs4/css/dataTables.bootstrap4.min.css' %}">
  <link rel="stylesheet" href="{% static 'plugins/datatables-responsive/css/responsive.bootstrap4.min.css' %}">
  <link rel="stylesheet" href="{% static 'plugins/datatables-buttons/css/buttons.bootstrap4.min.css' %}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{% static 'dist/css/adminlte.min.css' %}">
</head>
<body class="hold-transition sidebar-mini layout-fixed">
<div class="wrapper">

  <!-- Preloader -->
  <div class="preloader flex-column justify-content-center align-items-center">
    <img class="animation__shake" src="{% static 'dist/img/AdminLTELogo.png' %}" alt="AdminLTELogo" height="60" width="60">
  </div>

  <!-- Navbar -->
  <nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <a href="{% url 'homepage_url' %}" class="nav-link">Home</a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <a href="#" class="nav-link">Contact</a>
      </li>
    </ul>

    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">
      <!-- Navbar Search -->
      <li class="nav-item">
        <div class="navbar-search-block">
          <form class="form-inline">
            <div class="input-group input-group-sm">
              <input class="form-control form-control-navbar" type="search" placeholder="Search" aria-label="Search">
              <div class="input-group-append">
                <button class="btn btn-navbar" type="submit">
                  <i class="fas fa-search"></i>
                </button>
                <button class="btn btn-navbar" type="button" data-widget="navbar-search">
                  <i class="fas fa-times"></i>
                </button>
              </div>
            </div>
          </form>
        </div>
      </li>
      
      <!-- Notifications Dropdown Menu -->
      <li class="nav-item dropdown">
        <a class="nav-link" data-toggle="dropdown" href="#" title="sign out">
          <i class="fa fa-power-off"></i>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" data-widget="fullscreen" href="#" role="button">
          <i class="fas fa-expand-arrows-alt"></i>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" data-widget="control-sidebar" data-slide="true" href="#" role="button">
          <i class="fas fa-th-large"></i>
        </a>
      </li>
    </ul>
  </nav>
  <!-- /.navbar -->

  <!-- Main Sidebar Container -->
  <aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <a href="index3.html" class="brand-link">
      <img src="{% static 'dist/img/AdminLTELogo.png' %}" alt="AdminLTE Logo" class="brand-image img-circle elevation-3" style="opacity: .8">
      <span class="brand-text font-weight-light">Police</span>
    </a>

    <!-- Sidebar -->
    <div class="sidebar">
      <!-- Sidebar user panel (optional) -->
      <div class="user-panel mt-3 pb-3 mb-3 d-flex">
        <div class="image">
          <img src="{% static 'dist/img/user2-160x160.jpg' %}" class="img-circle elevation-2" alt="User Image">
        </div>
        <div class="info">
          <a href="#" class="d-block">{{request.user}}</a>
        </div>
      </div>

      <!-- SidebarSearch Form -->
      <div class="form-inline">
        <div class="input-group" data-widget="sidebar-search">
          <input class="form-control form-control-sidebar" type="search" placeholder="Search" aria-label="Search">
          <div class="input-group-append">
            <button class="btn btn-sidebar">
              <i class="fas fa-search fa-fw"></i>
            </button>
          </div>
        </div>
      </div>

      <!-- Sidebar Menu -->
      <nav class="mt-2">
        <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
          <!-- Add icons to the links using the .nav-icon class
               with font-awesome or any other icon font library -->
          <li class="nav-item menu-open">
            <a href="#" class="nav-link active">
              <i class="nav-icon fas fa-tachometer-alt"></i>
              <p>
                Dashboard
                <i class="right fas fa-angle-left"></i>
              </p>
            </a>
            <ul class="nav nav-treeview">
              <li class="nav-item">
                <a href="{% url 'dashboardco_url' %}" class="nav-link active">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Dashboard</p>
                </a>
              </li>
            </ul>
          </li>

          <li class="nav-item">
            <a href="#" class="nav-link">
              <i class="nav-icon fas fa-chart-pie"></i>
              <p>
              Case Management:
                <i class="right fas fa-angle-left"></i>
              </p>
            </a>
            <ul class="nav nav-treeview">
              <li class="nav-item">
                <a href="{% url 'caseassigned_url' %}" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Assigned Cases:</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="{% url 'casestatus_url' %}" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Case Status:</p>
                </a>
              </li>
            </ul>
          </li>

          <li class="nav-item">
            <a href="{% url 'myprofile_url' %}" class="nav-link">
              <i class="nav-icon fas fa-chart-pie"></i>
              <p>
              My Profile
              </p>
            </a>
          </li>
        </ul>
      </nav>
      <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
  </aside>

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1 class="m-0">Explorer Dashboard</h1>
          </div><!-- /.col -->
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="{% url 'homepage_url' %}">Home</a></li>
              <li class="breadcrumb-item active">Dashboard v1</li>
            </ol>
          </div><!-- /.col -->
        </div><!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
        <!-- Small boxes (Stat box) -->
      

        {% block content  %}
        
        {% endblock content %}
        


      </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->
  <footer class="main-footer">
    <strong>Copyright &copy; 2014-2021 <a href="https://adminlte.io">AdminLTE.io</a>.</strong>
    All rights reserved.
    <div class="float-right d-none d-sm-inline-block">
      <b>Version</b> 3.1.0
    </div>
  </footer>

  <!-- Control Sidebar -->
  <aside class="control-sidebar control-sidebar-dark">
    <!-- Control sidebar content goes here -->
  </aside>
  <!-- /.control-sidebar -->
</div>
<!-- ./wrapper -->

<!-- jQuery -->
<script src="{% static 'plugins/jquery/jquery.min.js' %}"></script>
<!-- jQuery UI 1.11.4 -->
<script src="{% static 'plugins/jquery-ui/jquery-ui.min.js' %}"></script>
<!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
<script>
  $.widget.bridge('uibutton', $.ui.button)
</script>
<!-- Bootstrap 4 -->
<script src="{% static 'plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<!-- ChartJS -->
<script src="{% static 'plugins/chart.js/Chart.min.js' %}"></script>
<!-- Sparkline -->
<script src="{% static 'plugins/sparklines/sparkline.js' %}"></script>
<!-- JQVMap -->
<script src="{% static 'plugins/jqvmap/jquery.vmap.min.js' %}"></script>
<script src="{% static 'plugins/jqvmap/maps/jquery.vmap.usa.js' %}"></script>
<!-- jQuery Knob Chart -->
<script src="{% static 'plugins/jquery-knob/jquery.knob.min.js' %}"></script>
<!-- daterangepicker -->
<script src="{% static 'plugins/moment/moment.min.js' %}"></script>
<script src="{% static 'plugins/daterangepicker/daterangepicker.js' %}"></script>
<!-- Tempusdominus Bootstrap 4 -->
<script src="{% static 'plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js' %}"></script>
<!-- Summernote -->
<script src="{% static 'plugins/summernote/summernote-bs4.min.js' %}"></script>
<!-- overlayScrollbars -->
<script src="{% static 'plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js' %}"></script>
<!-- AdminLTE App -->
<script src="{% static 'dist/js/adminlte.js' %}"></script>
<!-- AdminLTE for demo purposes -->
<script src="{% static 'dist/js/demo.js' %}"></script>
<!-- AdminLTE dashboard demo (This is only for demo purposes) -->
<script src="{% static 'dist/js/pages/dashboard.js' %}"></script>


<script src="{% static 'plugins/jquery/jquery.min.js' %}"></script>
<!-- Bootstrap 4 -->
<script src="{% static 'plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<!-- DataTables  & Plugins --> 

<!-- DataTables  & Plugins -->
<script src="{% static 'plugins/datatables/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'plugins/datatables-bs4/js/dataTables.bootstrap4.min.js' %}"></script>
<script src="{% static 'plugins/datatables-responsive/js/dataTables.responsive.min.js' %}"></script>
<script src="{% static 'plugins/datatables-responsive/js/responsive.bootstrap4.min.js' %}"></script>
<script src="{% static 'plugins/datatables-buttons/js/dataTables.buttons.min.js' %}"></script>
<script src="{% static 'plugins/datatables-buttons/js/buttons.bootstrap4.min.js' %}"></script>
<script src="{% static 'plugins/jszip/jszip.min.js' %}"></script>
<script src="{% static 'plugins/pdfmake/pdfmake.min.js' %}"></script>
<script src="{% static 'plugins/pdfmake/vfs_fonts.js' %}"></script>
<script src="{% static 'plugins/datatables-buttons/js/buttons.html5.min.js' %}"></script>
<script src="{% static 'plugins/datatables-buttons/js/buttons.print.min.js' %}"></script>
<script src="{% static 'plugins/datatables-buttons/js/buttons.colVis.min.js' %}"></script>

<!-- AdminLTE App -->
<script src="{% static 'dist/js/adminlte.min.js' %}"></script>
<!-- AdminLTE for demo purposes -->
<script src="{% static 'dist/js/demo.js' %}"></script>

<script>
  $(function () {
    $("#example1").DataTable({
      "responsive": true, "lengthChange": false, "autoWidth": false,
      "buttons": ["copy", "csv", "excel", "pdf", "print", "colvis"]
    }).buttons().container().appendTo('#example1_wrapper .col-md-6:eq(0)');
    $('#example2').DataTable({
      "paging": true,
      "lengthChange": false,
      "searching": false,
      "ordering": true,
      "info": true,
      "autoWidth": false,
      "responsive": true,
    });
  });
</script>

</body>
</html>

misogoro/templates/co/criminalcase_report.html
{% extends 'co/cobase.html' %}

{% block content %}


<h2>Criminal case report</h2>

{% endblock content %}

misogoro/templates/co/dashboardco.html
{% extends 'co/cobase.html' %}

{% block content %}

<div class="row">
    <div class="col-lg-3 col-6">
      <!-- small box -->
      <div class="small-box bg-info">
        <div class="inner">
          <h3>150</h3>

          <p>Total Police.</p>
        </div>
        <div class="icon">
          <i class="ion ion-bag"></i>
        </div>
      </div>
    </div>
    <!-- ./col -->
    <div class="col-lg-3 col-6">
      <!-- small box -->
      <div class="small-box bg-success">
        <div class="inner">
          <h3>53</h3>

          <p>Exploirers No</p>
        </div>
        <div class="icon">
          <i class="ion ion-stats-bars"></i>
        </div>
      </div>
    </div>
    <!-- ./col -->
    <div class="col-lg-3 col-6">
      <!-- small box -->
      <div class="small-box bg-warning">
        <div class="inner">
          <h3>44</h3>

          <p>Total No_cases.</p>
        </div>
        <div class="icon">
          <i class="ion ion-person-add"></i>
        </div>
      </div>
    </div>
    <!-- ./col -->
    <div class="col-lg-3 col-6">
      <!-- small box -->
      <div class="small-box bg-danger">
        <div class="inner">
          <h3>65</h3>

          <p>Active Cases</p>
        </div>
        <div class="icon">
          <i class="ion ion-pie-graph"></i>
        </div>
      </div>
    </div>
    <!-- ./col -->
  </div>

  {% endblock content%}

misogoro/templates/co/explorerreport.html
{% extends 'co/cobase.html' %}

{% block content %}


<h2>explorer report</h2>

{% endblock content %}

misogoro/templates/co/policereport.html
{% extends 'co/cobase.html' %}

{% block content %}


<h2>police report</h2>

{% endblock content %}